// components/TwitterTimeline.vue
<script lang="ts" setup>
useHead({
  script: [
    {
      type: "text/javascript",
      async: true,
      src: "https://platform.twitter.com/widgets.js",
    },
  ],
})
</script>

<template>
  <div>
    <h2 class="text-h5 text-center">
      おしらせ
    </h2>

    <q-card
      bordered
      flat
    >
      <q-card-section class="q-pa-sm">
        <q-scroll-area style="height: 300px;">
          <a
            class="twitter-timeline"
            data-lang="ja"
            data-width="100%"
            data-height="400"
            href="https://twitter.com/ms_golf?ref_src=twsrc%5Etfw"
          />
        </q-scroll-area>
      </q-card-section>
    </q-card>
  </div>
</template>

<style scoped></style>

// src/components/sections/twitter-timeline.tsx
'use client';

import { useEffect, useRef, useState } from "react";
import Script from "next/script";

export function TwitterTimeline() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    const timer = window.setTimeout(() => setIsMounted(true), 0);
    return () => window.clearTimeout(timer);
  }, []);

  return (
    <div
      ref={containerRef}
      className="h-[400px] overflow-y-auto rounded-md border border-stone-100 p-2"
    >
      {isMounted ? (
        <>
          <a
            className="twitter-timeline"
            href="https://twitter.com/ms_golf?ref_src=twsrc%5Etfw"
            data-height="360"
            data-width="100%"
          >
            Tweets by ms_golf
          </a>
          <Script
            id="twitter-wjs"
            src="https://platform.twitter.com/widgets.js"
            strategy="lazyOnload"
            charSet="utf-8"
          />
        </>
      ) : (
        <div className="flex h-full items-center justify-center text-sm text-stone-500">
          X（旧Twitter）の投稿を読み込んでいます…
        </div>
      )}
    </div>
  );
}
